name = "catch_the_cat"
compatibility_date = "2025-12-13"
workers_dev = false

routes = [{ pattern = "catch-the.cat", custom_domain = true }]

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
